version: '3'

services:
  webapi:
    image: delivery_service_api
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:80
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=sqldb;Initial Catalog=DeliveryService;Integrated Security=False;User Id=sa;Password=@@bbccdd123;MultipleActiveResultSets=True
    depends_on:
      - sqldb

  sqldb:
    image: "microsoft/mssql-server-linux"
    ports: 
      - 1433:1433 
    environment:
      SA_PASSWORD: "@@bbccdd123"
      ACCEPT_EULA: "Y"
